### ISSUE TITLE
Updated URLs in Makefile needed

### ISSUE THREAD

**Issue by TxEdgeMan** [EvanCarroll/db-Texas-Ethics-Commission#5]
Looks like the TEC has moved the location the files on their site.  Please update Makefile with the updated URLS:

download:
        curl --progress-bar \
                -o "$(DIR_TEC_DOCS)/TX_ERF13_7.pdf"                   "https://www.ethics.state.tx.us/data/search/cf/TX_ERF13_7.pdf"                                \
                -o "$(DIR_TEC_DOCS)/HowToImportContributionsAndExpenditures.pdf" "https://www.ethics.state.tx.us/data/filinginfo/HowToImportContributionsAndExpenditures.pdf"  \
                -o "$(DIR_TEC_DOCS)/CampaignFinanceCSVFileFormat.pdf" "https://www.ethics.state.tx.us/data/search/cf/CampaignFinanceCSVFileFormat.pdf" \
                -o "$(DIR_TEC_DOCS)/1295CertificatesCSVFormat.pdf"    "https://www.ethics.state.tx.us/data/search/1295/1295CertificatesCSVFormat.pdf"        \
                -o "$(DIR_DATA)/1295Certificates.csv"                 "https://www.ethics.state.tx.us/data/search/1295/1295Certificates.csv"                 \
                -o "$(DIR_DATA)/TEC_LA_CSV.zip"                       "https://www.ethics.state.tx.us/data/search/lobby/TEC_LA_CSV.zip"                       \
                -o "$(DIR_DATA)/TEC_CF_CSV.zip"                       "https://www.ethics.state.tx.us/data/search/cf/TEC_CF_CSV.zip";

Also, consider updating the instructions to run: make devgen  to rebuild the sql scripts so that any newly added files by TEC are included in the load into the DB.

Appreciate the tool!

**Comment by EvanCarroll** [comment]
Fixed.
