### ISSUE TITLE
Column definition for BigDecimal type update needed

### ISSUE THREAD

**Issue by TxEdgeMan** [EvanCarroll/db-Texas-Ethics-Commission#6]
This problem is seen by trying to import a record in the cover.csv file where a filed report contained an erroneous entry of 2104954824.00 in the unitemizedPledgeAmount.  The filer later realized the error and filed a corrected report.  

The Readme.txt file defines this field as follows:
21 unitemizedPledgeAmount                        BigDecimal 0000000000.00                     12 Total unitemized pledges     

The problem is in the Column.pm file  where the sub pg_type defines a BigDecimal as numeric(10,2).

We should be defining BigDecimal  as numeric(12,2).

Reasoning:  https://www.postgresql.org/docs/9.1/datatype-numeric.html
We use the following terms below: The scale of a numeric is the count of decimal digits in the fractional part, to the right of the decimal point. The **precision** of a numeric is the total count of significant digits in the whole number, that is, the **number of digits to both sides of the decimal point**. So the number 23.5141 has a precision of 6 and a scale of 4. Integers can be considered to have a scale of zero.

Both the maximum precision and the maximum scale of a numeric column can be configured. To declare a column of type numeric use the syntax:

NUMERIC(**precision,** scale)

**Comment by EvanCarroll** [comment]
I'm available for work on this project, but I probably won't be maintaining it any time soon. Pretty busy. I believe if the data is errant we should be removing it. Not changing the schema to accommodate it.

**Comment by TxEdgeMan** [comment]
I reported the error to the TEC.  The error was made by the filer for the Political Action Committee and corrected with an amended report later.  The user error is still included in their data as it was actually submitted to them and remains their for transparency and integrity of their data.  The number is still valid per their specs.

I think the suggested code change is still valid and have fixed the code locally, so you may update when time permits.
Thanks!
